#import "GameViewController.h"
#import "GLBMetalRenderer.h"
#import <MetalKit/MetalKit.h>
#import <GameController/GameController.h>
#import <ModelIO/ModelIO.h>
#import <UniformTypeIdentifiers/UniformTypeIdentifiers.h>
#import <QuartzCore/QuartzCore.h>

@interface GameViewController () <MTKViewDelegate, UIDocumentPickerDelegate>
@property id<MTLDevice> device; @property id<MTLCommandQueue> queue; @property GLBMetalRenderer *renderer;
@property NSDate *loadStart; @property UILabel *status; @property NSURL *persistentMapURL; @property CGPoint lastTouch; @property CADisplayLink *gameTick; @property CGPoint moveStick; @property float verticalVelocity; @property BOOL grounded;
@end
@implementation GameViewController
- (void)loadView { self.device=MTLCreateSystemDefaultDevice(); MTKView*v=[[MTKView alloc]initWithFrame:CGRectZero device:self.device];v.delegate=self;v.preferredFramesPerSecond=60;v.depthStencilPixelFormat=MTLPixelFormatDepth32Float;v.clearColor=MTLClearColorMake(.20,.36,.58,1);self.view=v; }
- (void)viewDidLoad { [super viewDidLoad]; self.queue=[self.device newCommandQueue]; MTKView*mv=(MTKView*)self.view; self.renderer=[[GLBMetalRenderer alloc]initWithDevice:self.device colorFormat:mv.colorPixelFormat depthFormat:mv.depthStencilPixelFormat]; self.status=[[UILabel alloc]initWithFrame:CGRectMake(18,18,700,40)];self.status.textColor=UIColor.whiteColor;self.status.text=@"CS2 iOS — cs_office";[self.view addSubview:self.status]; [self loadBundledOrPersistedMap]; self.gameTick=[CADisplayLink displayLinkWithTarget:self selector:@selector(updatePlayer:)];[self.gameTick addToRunLoop:NSRunLoop.mainRunLoop forMode:NSRunLoopCommonModes]; [[NSNotificationCenter defaultCenter]addObserver:self selector:@selector(controller:) name:GCControllerDidConnectNotification object:nil];[GCController startWirelessControllerDiscoveryWithCompletionHandler:^{}]; }
- (NSURL*)storedMapURL { NSURL*d=[[[NSFileManager defaultManager] URLsForDirectory:NSApplicationSupportDirectory inDomains:NSUserDomainMask] firstObject]; [[NSFileManager defaultManager] createDirectoryAtURL:d withIntermediateDirectories:YES attributes:nil error:nil]; return [d URLByAppendingPathComponent:@"cs_office.glb"]; }
- (void)loadBundledOrPersistedMap { NSURL*b=[[NSBundle mainBundle] URLForResource:@"n0" withExtension:@"glb" subdirectory:@"PrivateAssets/Maps/cs_office"]; if(b){self.status.text=@"Loading integrated cs_office…";[self loadMapURL:b];return;} NSURL*u=[self storedMapURL]; if([[NSFileManager defaultManager] fileExistsAtPath:u.path]){self.status.text=@"Loading saved cs_office…";[self loadMapURL:u];return;} self.status.text=@"No integrated map found"; }
- (void)applySpawnBesideMap:(NSURL*)mapURL { NSURL*s=[mapURL.URLByDeletingLastPathComponent URLByAppendingPathComponent:@"spawn.json"];NSData*d=[NSData dataWithContentsOfURL:s];if(!d)return;NSDictionary*j=[NSJSONSerialization JSONObjectWithData:d options:0 error:nil];NSArray*p=j[@"position"];NSNumber*y=j[@"yaw"],*q=j[@"pitch"];if(p.count!=3||!y)return;self.renderer.cameraPosition=(vector_float3){[p[0] floatValue],[p[1] floatValue],[p[2] floatValue]};self.renderer.cameraYaw=y.floatValue;self.renderer.cameraPitch=q?q.floatValue:0;NSLog(@"[CS2iOS][Step5] private spawn applied");}
- (void)loadMapURL:(NSURL*)x { self.loadStart=[NSDate date]; NSError*err=nil; BOOL ok=[self.renderer loadURL:x error:&err]; NSTimeInterval t=-self.loadStart.timeIntervalSinceNow; if(!ok){self.status.text=[NSString stringWithFormat:@"Map load failed: %@",err.localizedDescription?:@"no GLB primitives"];NSLog(@"[CS2iOS][Step4] direct GLB FAILED %@",err);return;} [self applySpawnBesideMap:x];self.status.text=[NSString stringWithFormat:@"cs_office loaded %.2fs • primitives %lu",t,(unsigned long)self.renderer.primitiveCount];NSLog(@"[CS2iOS][Step5] direct GLB loaded primitives=%lu load=%.3fs",(unsigned long)self.renderer.primitiveCount,t); }
- (void)importMap { UIDocumentPickerViewController*p=[[UIDocumentPickerViewController alloc]initForOpeningContentTypes:@[[UTType typeWithFilenameExtension:@"glb"]]];p.delegate=self;[self presentViewController:p animated:YES completion:nil]; }
- (void)documentPicker:(UIDocumentPickerViewController*)c didPickDocumentsAtURLs:(NSArray<NSURL*>*)u { NSURL*x=u.firstObject;if(!x)return;BOOL a=[x startAccessingSecurityScopedResource]; NSURL*dst=[self storedMapURL]; [[NSFileManager defaultManager] removeItemAtURL:dst error:nil]; NSError*err=nil; BOOL ok=[[NSFileManager defaultManager] copyItemAtURL:x toURL:dst error:&err]; if(a)[x stopAccessingSecurityScopedResource]; if(!ok){self.status.text=[NSString stringWithFormat:@"Import failed: %@",err.localizedDescription];NSLog(@"[CS2iOS][Step4] persist FAILED %@",err);return;} [self loadMapURL:dst]; }
- (void)controller:(NSNotification*)n { NSLog(@"[CS2iOS] controller=%lu",(unsigned long)GCController.controllers.count); }
- (void)touchesBegan:(NSSet<UITouch*>*)t withEvent:(UIEvent*)e { UITouch*u=[t anyObject];CGPoint p=[u locationInView:self.view];self.lastTouch=p;if(p.x<self.view.bounds.size.width*.45)self.moveStick=p; }
- (void)touchesMoved:(NSSet<UITouch*>*)t withEvent:(UIEvent*)e { CGPoint p=[[t anyObject] locationInView:self.view];float dx=p.x-self.lastTouch.x,dy=p.y-self.lastTouch.y;if(p.x>=self.view.bounds.size.width*.45){self.renderer.cameraYaw+=dx*.004f;self.renderer.cameraPitch=fmaxf(-1.35f,fminf(1.35f,self.renderer.cameraPitch-dy*.004f));}else{float sy=sinf(self.renderer.cameraYaw),cy=cosf(self.renderer.cameraYaw);vector_float3 q=self.renderer.cameraPosition;q.x+=(sy*(-dy)+cy*dx)*.012f;q.z+=(-cy*(-dy)+sy*dx)*.012f;self.renderer.cameraPosition=[self.renderer constrainPlayerPosition:q];}self.lastTouch=p; }
- (void)touchesEnded:(NSSet<UITouch*>*)t withEvent:(UIEvent*)e {}
- (void)pressesBegan:(NSSet<UIPress*>*)presses withEvent:(UIPressesEvent*)event { for(UIPress*p in presses){if(p.type==UIPressTypeSelect&&self.grounded){self.verticalVelocity=4.8f;self.grounded=NO;}}[super pressesBegan:presses withEvent:event]; }
- (void)updatePlayer:(CADisplayLink*)dl { float dt=fminf(dl.duration,1.0/30.0),x=0,y=0;GCController*c=GCController.current?:GCController.controllers.firstObject;GCExtendedGamepad*g=c.extendedGamepad;if(g){x=g.leftThumbstick.xAxis.value;y=g.leftThumbstick.yAxis.value;if(fabsf(x)<.12f)x=0;if(fabsf(y)<.12f)y=0;if(g.buttonA.isPressed&&self.grounded){self.verticalVelocity=4.8f;self.grounded=NO;}self.renderer.cameraYaw+=g.rightThumbstick.xAxis.value*2.2f*dt;self.renderer.cameraPitch=fmaxf(-1.35f,fminf(1.35f,self.renderer.cameraPitch+g.rightThumbstick.yAxis.value*1.8f*dt));}vector_float3 p=self.renderer.cameraPosition;self.verticalVelocity-=9.8f*dt;p.y+=self.verticalVelocity*dt;float sy=sinf(self.renderer.cameraYaw),cy=cosf(self.renderer.cameraYaw),sp=4.5f*dt;p.x+=(sy*y+cy*x)*sp;p.z+=(-cy*y+sy*x)*sp;vector_float3 q=[self.renderer constrainPlayerPosition:p];if(q.y>p.y){self.verticalVelocity=0;self.grounded=YES;}else self.grounded=NO;self.renderer.cameraPosition=q;}
- (void)mtkView:(MTKView*)v drawableSizeWillChange:(CGSize)s{}
- (void)drawInMTKView:(MTKView*)v { MTLRenderPassDescriptor*p=v.currentRenderPassDescriptor;id<CAMetalDrawable>d=v.currentDrawable;if(!p||!d)return;id<MTLCommandBuffer>cb=[self.queue commandBuffer];id<MTLRenderCommandEncoder>e=[cb renderCommandEncoderWithDescriptor:p];[self.renderer draw:e drawableSize:v.drawableSize];[e endEncoding];[cb presentDrawable:d];[cb commit]; }
- (UIInterfaceOrientationMask)supportedInterfaceOrientations{return UIInterfaceOrientationMaskLandscape;}
@end
